export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES';
export const ADD_TIME_OFF = 'ADD_TIME_OFF';
export const REMOVE_TIME_OFF = 'REMOVE_TIME_OFF';
